--[[
	Career Events
	All events here REQUIRE the player to have a job (requiresJob = true)
]]

local Career = {}

Career.events = {
	-- ══════════════════════════════════════════════════════════════════════════════
	-- GENERAL WORKPLACE EVENTS
	-- ══════════════════════════════════════════════════════════════════════════════
	{
		id = "workplace_conflict",
		title = "Office Drama",
		emoji = "😤",
		text = "A coworker has been taking credit for your work.",
		question = "How do you handle this?",
		minAge = 18, maxAge = 65,
		baseChance = 0.4,
		cooldown = 3,
		requiresJob = true,
		choices = {
			{ text = "Confront them directly", effects = { Happiness = 3 }, setFlags = { workplace_confrontation = true }, feedText = "You called them out. The tension is thick." },
			{ text = "Document everything, report to HR", effects = { Smarts = 2 }, feedText = "You took the professional route." },
			{ text = "Let it go this time", effects = { Happiness = -3 }, feedText = "You let it slide. But you're watching now." },
			{ text = "Beat them at their own game", effects = { Smarts = 3 }, feedText = "Two can play at office politics." },
		},
	},
	{
		id = "promotion_opportunity",
		title = "Opportunity Knocks",
		emoji = "📈",
		text = "A promotion opportunity has opened up at work.",
		question = "Do you go for it?",
		minAge = 20, maxAge = 60,
		baseChance = 0.4,
		cooldown = 3,
		requiresJob = true,
		choices = {
			{ text = "Apply and compete hard", effects = { Smarts = 2, Money = 500, Health = -2 }, setFlags = { sought_promotion = true }, feedText = "You threw your hat in the ring!" },
			{ text = "Apply casually", effects = { Money = 250 }, feedText = "You applied but kept expectations low." },
			{ text = "Not interested", effects = { Happiness = 2 }, feedText = "You're happy where you are." },
		},
	},
	{
		id = "layoff_threat",
		title = "Company Restructuring",
		emoji = "📉",
		text = "Your company is laying people off. Your position might be at risk.",
		question = "What do you do?",
		minAge = 22, maxAge = 60,
		baseChance = 0.3,
		cooldown = 5,
		requiresJob = true,
		choices = {
			{ text = "Work extra hard to prove value", effects = { Health = -5, Smarts = 2, Money = 200 }, feedText = "You worked overtime to secure your position." },
			{ text = "Start job hunting quietly", effects = { Smarts = 2 }, setFlags = { job_hunting = true }, feedText = "You're exploring other options." },
			{ text = "Accept severance if offered", effects = { Money = 2000, Happiness = -5 }, setFlags = { between_jobs = true }, feedText = "You took the package. Time for something new." },
			{ text = "Trust it will work out", effects = { Happiness = 2 }, feedText = "You hoped for the best..." },
		},
	},
	{
		id = "boss_from_hell",
		title = "Difficult Manager",
		emoji = "👹",
		text = "Your new manager is making work miserable.",
		question = "How do you cope?",
		minAge = 18, maxAge = 60,
		baseChance = 0.4,
		cooldown = 4,
		requiresJob = true,
		choices = {
			{ text = "Keep your head down", effects = { Happiness = -5, Health = -3 }, feedText = "You endured in silence." },
			{ text = "Address it with HR", effects = { Happiness = 3 }, feedText = "You reported the issues." },
			{ text = "Find a new job", effects = { Happiness = 5 }, setFlags = { job_hunting = true }, feedText = "Life's too short for bad bosses." },
			{ text = "Adapt and learn to work with them", effects = { Smarts = 3, Happiness = 2 }, feedText = "You figured out how to manage the relationship." },
		},
	},
	{
		id = "work_achievement",
		title = "Major Achievement",
		emoji = "🏆",
		text = "You accomplished something significant at work!",
		question = "What was it?",
		minAge = 20, maxAge = 65,
		baseChance = 0.3,
		cooldown = 3,
		requiresJob = true,
		requiresStats = { Smarts = { min = 50 } },
		choices = {
			{ text = "Landed a big client/deal", effects = { Happiness = 10, Money = 1000, Smarts = 2 }, setFlags = { big_achiever = true }, feedText = "You closed a major deal!" },
			{ text = "Solved a critical problem", effects = { Happiness = 8, Smarts = 5 }, setFlags = { problem_solver = true }, feedText = "You saved the day with your solution!" },
			{ text = "Got recognized by leadership", effects = { Happiness = 10, Money = 500 }, feedText = "The executives noticed your work!" },
			{ text = "Mentored someone successfully", effects = { Happiness = 8, Smarts = 2 }, setFlags = { mentor = true }, feedText = "You helped someone grow in their career!" },
		},
	},
	{
		id = "business_trip",
		title = "Business Travel",
		emoji = "✈️",
		text = "You've been selected for an important business trip.",
		question = "How do you approach it?",
		minAge = 22, maxAge = 60,
		baseChance = 0.4,
		cooldown = 2,
		requiresJob = true,
		choices = {
			{ text = "All business, impress the clients", effects = { Smarts = 3, Money = 300, Health = -2 }, feedText = "You crushed it professionally!" },
			{ text = "Balance work and exploration", effects = { Happiness = 5, Smarts = 2 }, feedText = "You saw some sights while getting work done!" },
			{ text = "Network at every opportunity", effects = { Smarts = 2 }, setFlags = { strong_network = true }, feedText = "You made valuable connections!" },
		},
	},
	{
		id = "career_crossroads",
		title = "Career Crossroads",
		emoji = "🛤️",
		text = "You're at a turning point in your career.",
		question = "What path do you take?",
		minAge = 28, maxAge = 45,
		baseChance = 0.5,
		cooldown = 5,
		requiresJob = true,
		choices = {
			{ text = "Push for a promotion", effects = { Smarts = 2, Money = 500, Happiness = 5 }, feedText = "You went for the promotion!" },
			{ text = "Change companies for better pay", effects = { Money = 1000, Happiness = 3 }, setFlags = { job_hopper = true }, feedText = "You switched jobs for a raise!" },
			{ text = "Pivot to a new career entirely", effects = { Smarts = 5, Money = -1000, Happiness = 5 }, setFlags = { career_changer = true }, feedText = "You're starting over in a new field!" },
			{ text = "Stay the course", effects = { Happiness = 2 }, feedText = "You're content where you are." },
		},
	},

	-- ══════════════════════════════════════════════════════════════════════════════
	-- CAREER-SPECIFIC EVENTS (Require specific job categories)
	-- ══════════════════════════════════════════════════════════════════════════════
	{
		id = "tech_innovation",
		title = "Tech Breakthrough",
		emoji = "💡",
		text = "You have an idea for a revolutionary new feature/product.",
		question = "What do you do with it?",
		minAge = 20, maxAge = 50,
		baseChance = 0.3,
		cooldown = 5,
		requiresJob = true,
		requiresJobCategory = "tech",
		choices = {
			{ text = "Pitch it to your company", effects = { Happiness = 8, Money = 1000, Smarts = 3 }, feedText = "You pitched your big idea!" },
			{ text = "Start your own company with it", effects = { Happiness = 10, Money = -3000 }, setFlags = { entrepreneur = true, startup_founder = true }, feedText = "You're going out on your own!" },
			{ text = "Keep developing it as a side project", effects = { Smarts = 5, Health = -2 }, setFlags = { side_hustler = true }, feedText = "You're building something on the side." },
			{ text = "Forget it, too risky", effects = { Happiness = -3 }, feedText = "The idea faded away..." },
		},
	},
	{
		id = "medical_save",
		title = "Critical Moment",
		emoji = "🏥",
		text = "A patient's life depends on your quick decision.",
		question = "What do you do?",
		minAge = 28, maxAge = 65,
		baseChance = 0.4,
		cooldown = 3,
		requiresJob = true,
		requiresJobCategory = "medical",
		choices = {
			{ text = "Trust your training and act", effects = { Happiness = 10, Smarts = 5 }, feedText = "You made a split-second decision that saved them!" },
			{ text = "Consult with colleagues first", effects = { Smarts = 3, Happiness = 5 }, feedText = "Team medicine saved the day." },
			{ text = "Follow strict protocol", effects = { Smarts = 2 }, feedText = "By the book... it worked." },
		},
	},
	{
		id = "legal_case",
		title = "The Big Case",
		emoji = "⚖️",
		text = "You've been assigned a high-profile case.",
		question = "How do you approach it?",
		minAge = 27, maxAge = 65,
		baseChance = 0.4,
		cooldown = 3,
		requiresJob = true,
		requiresJobCategory = "law",
		choices = {
			{ text = "Work around the clock", effects = { Smarts = 5, Money = 2000, Health = -5 }, setFlags = { legal_star = true }, feedText = "You gave it everything!" },
			{ text = "Delegate and manage", effects = { Smarts = 3, Money = 1000 }, feedText = "Leadership got the job done." },
			{ text = "Find an unexpected angle", effects = { Smarts = 7, Happiness = 5, Money = 1500 }, feedText = "Your creative approach paid off!" },
		},
	},
	{
		id = "creative_block",
		title = "Creative Block",
		emoji = "🎨",
		text = "You're stuck. The inspiration just won't come.",
		question = "How do you push through?",
		minAge = 20, maxAge = 60,
		baseChance = 0.5,
		cooldown = 2,
		requiresJob = true,
		requiresJobCategory = "creative",
		choices = {
			{ text = "Take a break and recharge", effects = { Happiness = 5, Health = 3, Smarts = 2 }, feedText = "Rest brought the creativity back." },
			{ text = "Push through with discipline", effects = { Smarts = 3, Happiness = -3, Health = -2 }, feedText = "Discipline overcame the block." },
			{ text = "Seek inspiration from others", effects = { Smarts = 4, Happiness = 3 }, feedText = "Collaboration sparked new ideas." },
			{ text = "Try something completely different", effects = { Happiness = 5, Smarts = 5 }, setFlags = { versatile_creative = true }, feedText = "A new direction opened new doors!" },
		},
	},
	{
		id = "athlete_injury",
		title = "Sports Injury",
		emoji = "🤕",
		text = "You've sustained an injury that could affect your career.",
		question = "How do you handle it?",
		minAge = 18, maxAge = 40,
		baseChance = 0.5,
		cooldown = 3,
		requiresJob = true,
		requiresJobCategory = "sports",
		choices = {
			{ text = "Proper rehab, take time to heal", effects = { Health = 5, Money = -500, Happiness = -3 }, setFlags = { recovered_athlete = true }, feedText = "You took recovery seriously." },
			{ text = "Rush back too soon", effects = { Health = -10, Happiness = -5 }, setFlags = { chronic_injury = true }, feedText = "Coming back too fast made it worse..." },
			{ text = "Use it as motivation", effects = { Health = 3, Smarts = 2, Happiness = 5 }, setFlags = { comeback_story = true }, feedText = "You turned the setback into fuel!" },
		},
	},

	-- ══════════════════════════════════════════════════════════════════════════════
	-- ENTREPRENEURSHIP
	-- ══════════════════════════════════════════════════════════════════════════════
	{
		id = "business_opportunity",
		title = "Business Opportunity",
		emoji = "💰",
		text = "Someone approaches you with a business opportunity.",
		question = "Is it legit?",
		minAge = 22, maxAge = 60,
		baseChance = 0.3,
		cooldown = 4,
		choices = {
			{ text = "It's a great opportunity! Invest!", effects = { Money = 3000, Happiness = 8 }, setFlags = { investor = true }, feedText = "You took a chance on the opportunity!" },
			{ text = "Do thorough due diligence first", effects = { Smarts = 3, Money = 1000 }, feedText = "You researched carefully before deciding." },
			{ text = "If it sounds too good to be true...", effects = { Happiness = 2, Smarts = 2 }, feedText = "You wisely passed on the 'opportunity.'" },
			{ text = "It's a scam! Report it!", effects = { Smarts = 3 }, feedText = "You recognized and reported the scam." },
		},
	},
	{
		id = "side_business",
		title = "Side Business Idea",
		emoji = "💡",
		text = "You've been working on a side business that's gaining traction.",
		question = "What's next?",
		minAge = 25, maxAge = 55,
		baseChance = 0.3,
		cooldown = 4,
		requiresFlags = { entrepreneur = true },
		choices = {
			{ text = "Go full-time on it", effects = { Happiness = 10, Money = 2000 }, setFlags = { full_time_entrepreneur = true }, feedText = "You quit your job to focus on your business!" },
			{ text = "Keep it as a side income", effects = { Money = 500, Happiness = 5, Health = -2 }, feedText = "Extra income is nice!" },
			{ text = "Sell it", effects = { Money = 5000, Happiness = 5 }, feedText = "You sold your side business for a nice profit!" },
			{ text = "Find investors", effects = { Money = 3000, Smarts = 2 }, setFlags = { has_investors = true }, feedText = "You brought on investors to grow!" },
		},
	},
	{
		id = "career_recognition",
		title = "Industry Recognition",
		emoji = "🏅",
		text = "You've been nominated for an industry award!",
		question = "How do you feel?",
		minAge = 30, maxAge = 65,
		baseChance = 0.2,
		cooldown = 5,
		requiresJob = true,
		requiresStats = { Smarts = { min = 70 } },
		choices = {
			{ text = "Honored and humbled", effects = { Happiness = 10, Smarts = 2 }, setFlags = { award_winner = true }, feedText = "You were recognized for your contributions!" },
			{ text = "It's about time!", effects = { Happiness = 8 }, setFlags = { award_winner = true }, feedText = "Finally, the recognition you deserved!" },
			{ text = "Use it to help others", effects = { Happiness = 12, Smarts = 3 }, setFlags = { award_winner = true, gives_back = true }, feedText = "You used your platform to lift others." },
		},
	},
}

return Career
