-- LifeEvents/Childhood.lua
-- Rich childhood events (ages 0-12) that shape personality and hint at future paths

local ChildhoodEvents = {}

ChildhoodEvents.events = {
	-- ══════════════════════════════════════════════════════════════════════
	-- BABY & TODDLER (Ages 0-4) - Formative moments, parent interactions
	-- ══════════════════════════════════════════════════════════════════════

	{
		id = "first_words",
		title = "First Words",
		emoji = "👶",
		category = "milestone",
		text = "Your parents are excited - you just spoke your first word!",
		question = "What did you say?",
		minAge = 1, maxAge = 2,
		oneTime = true,
		priority = "high",
		isMilestone = true,
		choices = {
			{
				text = '"Mama"',
				effects = { Happiness = 5 },
				setFlags = { first_word = "mama" },
				feedText = "You said your first word: 'Mama'. Your mother was overjoyed.",
			},
			{
				text = '"Dada"',
				effects = { Happiness = 5 },
				setFlags = { first_word = "dada" },
				feedText = "You said your first word: 'Dada'. Your father beamed with pride.",
			},
			{
				text = '"No!"',
				effects = { Happiness = 3 },
				setFlags = { first_word = "no", rebellious_streak = true },
				feedText = "Your first word was 'No!' - already showing your independent spirit.",
			},
			{
				text = 'An attempt at the dog\'s name',
				effects = { Happiness = 4 },
				setFlags = { first_word = "pet", animal_lover = true },
				hintCareer = "veterinary",
				feedText = "You tried to say the dog's name. Pets already have your heart.",
			},
		},
	},

	{
		id = "first_steps",
		title = "First Steps",
		emoji = "🚶",
		category = "milestone",
		text = "You're standing up and ready to take your first steps!",
		question = "How do you approach this challenge?",
		minAge = 1, maxAge = 2,
		oneTime = true,
		priority = "high",
		isMilestone = true,
		choices = {
			{
				text = "Carefully and cautiously",
				effects = { Smarts = 2 },
				setFlags = { cautious_personality = true },
				feedText = "You took careful, measured first steps. Safety first!",
			},
			{
				text = "Boldly charge forward",
				effects = { Health = -2, Happiness = 5 },
				setFlags = { adventurous_spirit = true },
				feedText = "You ran before you could walk - and took a tumble. But you got right back up!",
			},
			{
				text = "Wait for encouragement",
				effects = { Happiness = 3 },
				setFlags = { seeks_approval = true },
				feedText = "With your parents cheering, you walked right into their arms.",
			},
		},
	},

	{
		id = "toddler_tantrum",
		title = "The Terrible Twos",
		emoji = "😤",
		category = "behavior",
		text = "You want a toy at the store, but your parents said no.",
		question = "What do you do?",
		minAge = 2, maxAge = 3,
		baseChance = 0.8,
		cooldown = 2,
		choices = {
			{
				text = "Throw a massive tantrum",
				effects = { Happiness = -5 },
				setFlags = { throws_tantrums = true },
				feedText = "You threw an epic tantrum. Your parents were mortified.",
			},
			{
				text = "Pout but accept it",
				effects = { Happiness = -2, Smarts = 1 },
				setFlags = { learns_patience = true },
				feedText = "You pouted, but learned that tantrums don't always work.",
			},
			{
				text = "Try to negotiate",
				effects = { Smarts = 3 },
				setFlags = { natural_negotiator = true },
				hintCareer = "law",
				feedText = "Even at age 2, you tried to make a deal. Future lawyer?",
			},
			{
				text = "Get distracted by something else",
				effects = { Happiness = 2 },
				setFlags = { easily_distracted = true },
				feedText = "A shiny object caught your eye. Crisis averted.",
			},
		},
	},

	{
		id = "preschool_start",
		title = "First Day of Preschool",
		emoji = "🎒",
		category = "education",
		text = "It's your first day of preschool! Your parents drop you off at the colorful building.",
		question = "How do you handle being away from home?",
		minAge = 3, maxAge = 4,
		oneTime = true,
		priority = "high",
		choices = {
			{
				text = "Cry and cling to mom/dad",
				effects = { Happiness = -5 },
				feedText = "The first day was rough. Lots of tears, but you survived.",
			},
			{
				text = "March in confidently",
				effects = { Happiness = 5, Smarts = 2 },
				setFlags = { socially_confident = true },
				feedText = "You walked in like you owned the place. New friends incoming!",
			},
			{
				text = "Quietly observe the other kids",
				effects = { Smarts = 3 },
				setFlags = { observant = true },
				hintCareer = "science",
				feedText = "You watched everything carefully. An analytical mind is forming.",
			},
			{
				text = "Immediately find the art supplies",
				effects = { Happiness = 5, Looks = 1 },
				setFlags = { artistic_interest = true },
				hintCareer = "creative",
				feedText = "You made a beeline for the crayons. A creative soul!",
			},
		},
	},

	{
		id = "imaginary_friend",
		title = "Imaginary Friend",
		emoji = "👻",
		category = "social",
		text = "You've been spending a lot of time talking to your 'invisible friend.'",
		question = "Who is your imaginary friend?",
		minAge = 3, maxAge = 5,
		oneTime = true,
		baseChance = 0.6,
		choices = {
			{
				text = "A brave superhero",
				effects = { Happiness = 5 },
				setFlags = { hero_complex = true },
				feedText = "Your imaginary superhero friend makes you feel invincible.",
			},
			{
				text = "A wise wizard",
				effects = { Smarts = 3 },
				setFlags = { loves_fantasy = true },
				hintCareer = "creative",
				feedText = "Your wizard friend teaches you 'magic' - really just creative problem solving.",
			},
			{
				text = "A friendly animal",
				effects = { Happiness = 3 },
				setFlags = { animal_lover = true },
				hintCareer = "veterinary",
				feedText = "Your animal friend understands you like no human does.",
			},
			{
				text = "I don't need imaginary friends",
				effects = { Smarts = 2 },
				setFlags = { pragmatic = true },
				feedText = "You prefer real friends. Very practical for your age.",
			},
		},
	},

	-- ══════════════════════════════════════════════════════════════════════
	-- EARLY CHILDHOOD (Ages 5-8) - School, friendships, discovering interests
	-- ══════════════════════════════════════════════════════════════════════

	{
		id = "stage_transition_child",
		title = "Starting Elementary School",
		emoji = "🏫",
		category = "milestone",
		text = "You're starting elementary school! This is a big step into the wider world.",
		question = "What are you most excited about?",
		minAge = 5, maxAge = 5,
		oneTime = true,
		priority = "high",
		isMilestone = true,
		choices = {
			{
				text = "Making new friends",
				effects = { Happiness = 5 },
				setFlags = { social_focus = true },
				feedText = "You're ready to meet tons of new friends!",
			},
			{
				text = "Learning to read",
				effects = { Smarts = 5 },
				setFlags = { academic_focus = true },
				hintCareer = "education",
				feedText = "Books are about to become your best friends.",
			},
			{
				text = "Recess and sports",
				effects = { Health = 3, Happiness = 3 },
				setFlags = { athletic_focus = true },
				hintCareer = "sports",
				feedText = "You can't wait to run around the playground!",
			},
			{
				text = "Art class",
				effects = { Happiness = 4, Looks = 2 },
				setFlags = { artistic_focus = true },
				hintCareer = "creative",
				feedText = "You're excited to express yourself creatively.",
			},
		},
	},

	{
		id = "first_best_friend",
		title = "A New Best Friend",
		emoji = "🤝",
		category = "social",
		text = "You've been hanging out with a kid from class a lot. They might become your best friend!",
		question = "What do you two do together?",
		minAge = 5, maxAge = 8,
		oneTime = true,
		choices = {
			{
				text = "Play imaginative games",
				effects = { Happiness = 5, Smarts = 2 },
				setFlags = { creative_play = true, has_best_friend = true },
				feedText = "You and your new best friend create entire worlds together.",
			},
			{
				text = "Build things with blocks/Legos",
				effects = { Smarts = 5, Happiness = 3 },
				setFlags = { builder = true, has_best_friend = true },
				hintCareer = "tech",
				feedText = "You're a building team! Engineering minds in the making.",
			},
			{
				text = "Play sports outside",
				effects = { Health = 5, Happiness = 3 },
				setFlags = { sporty = true, has_best_friend = true },
				hintCareer = "sports",
				feedText = "You and your friend are always running around outside.",
			},
			{
				text = "Read and explore together",
				effects = { Smarts = 5 },
				setFlags = { curious = true, has_best_friend = true },
				hintCareer = "science",
				feedText = "You're partners in curiosity, always discovering new things.",
			},
		},
	},

	{
		id = "school_bully",
		title = "Trouble on the Playground",
		emoji = "😠",
		category = "conflict",
		text = "An older kid at school has been picking on you and other kids.",
		question = "How do you handle this?",
		minAge = 6, maxAge = 10,
		baseChance = 0.6,
		cooldown = 3,
		choices = {
			{
				text = "Stand up to them",
				effects = { Happiness = 5, Health = {-5, 5} },
				setFlags = { brave = true },
				feedText = "You stood up to the bully. It was scary, but you earned respect.",
			},
			{
				text = "Tell a teacher",
				effects = { Happiness = 2, Smarts = 2 },
				setFlags = { trusts_authority = true },
				feedText = "You told an adult. The bully got in trouble.",
			},
			{
				text = "Avoid them completely",
				effects = { Happiness = -3 },
				setFlags = { conflict_avoidant = true },
				feedText = "You learned which hallways to avoid. Safety first.",
			},
			{
				text = "Try to befriend them",
				effects = { Happiness = {-2, 5}, Smarts = 3 },
				setFlags = { peacemaker = true },
				hintCareer = "social_work",
				feedText = "You tried to understand why they're mean. Sometimes kindness works.",
			},
		},
	},

	{
		id = "class_pet",
		title = "Classroom Pet",
		emoji = "🐹",
		category = "school",
		text = "Your classroom got a new pet hamster! The teacher needs someone to care for it.",
		question = "Do you volunteer?",
		minAge = 6, maxAge = 9,
		baseChance = 0.7,
		cooldown = 5,
		choices = {
			{
				text = "Eagerly volunteer",
				effects = { Happiness = 5 },
				setFlags = { responsible = true, animal_lover = true },
				hintCareer = "veterinary",
				feedText = "You became the official hamster caretaker. Such responsibility!",
			},
			{
				text = "Help out sometimes",
				effects = { Happiness = 3 },
				feedText = "You helped take care of the hamster when you could.",
			},
			{
				text = "Nah, too much work",
				effects = { },
				feedText = "You preferred to admire the hamster from afar.",
			},
		},
	},

	{
		id = "talent_show",
		title = "School Talent Show",
		emoji = "🎭",
		category = "performance",
		text = "The school is having a talent show! Will you participate?",
		question = "What will you do?",
		minAge = 6, maxAge = 11,
		baseChance = 0.8,
		cooldown = 3,
		choices = {
			{
				text = "Sing a song",
				effects = { Happiness = {-3, 10}, Looks = 2 },
				setFlags = { performer = true },
				hintCareer = "entertainment",
				feedText = "You sang your heart out on stage!",
			},
			{
				text = "Do a magic trick",
				effects = { Smarts = 3, Happiness = 5 },
				setFlags = { showman = true },
				feedText = "Your magic trick amazed the audience!",
			},
			{
				text = "Tell jokes",
				effects = { Happiness = 7 },
				setFlags = { class_clown = true },
				hintCareer = "entertainment",
				feedText = "You had everyone laughing. Natural comedian!",
			},
			{
				text = "Watch from the audience",
				effects = { },
				feedText = "You cheered on your classmates from your seat.",
			},
			{
				text = "Help backstage",
				effects = { Smarts = 2, Happiness = 3 },
				setFlags = { behind_scenes = true },
				feedText = "You helped make the show happen from behind the curtain.",
			},
		},
	},

	{
		id = "science_fair",
		title = "Science Fair Project",
		emoji = "🔬",
		category = "education",
		text = "It's science fair season! What kind of project will you do?",
		question = "Choose your project:",
		minAge = 7, maxAge = 11,
		baseChance = 0.7,
		cooldown = 3,
		choices = {
			{
				text = "Volcano eruption",
				effects = { Smarts = 3, Happiness = 5 },
				setFlags = { likes_chemistry = true },
				hintCareer = "science",
				feedText = "Your baking soda volcano was the hit of the fair!",
			},
			{
				text = "Growing plants experiment",
				effects = { Smarts = 5 },
				setFlags = { patient_researcher = true },
				hintCareer = "science",
				feedText = "You carefully documented how different conditions affect plant growth.",
			},
			{
				text = "Build a simple robot",
				effects = { Smarts = 7 },
				setFlags = { tech_enthusiast = true },
				hintCareer = "tech",
				feedText = "Your robot impressed the judges. Future engineer!",
			},
			{
				text = "Psychology experiment",
				effects = { Smarts = 5 },
				setFlags = { understands_people = true },
				hintCareer = "medical",
				feedText = "You studied how people make decisions. Fascinating results!",
			},
			{
				text = "Skip it",
				effects = { Smarts = -2 },
				feedText = "You didn't participate in the science fair this year.",
			},
		},
	},

	{
		id = "sports_tryout",
		title = "Sports Team Tryouts",
		emoji = "⚽",
		category = "sports",
		text = "Tryouts for the youth sports league are coming up!",
		question = "Which sport will you try?",
		minAge = 6, maxAge = 11,
		baseChance = 0.7,
		cooldown = 2,
		choices = {
			{
				text = "Soccer",
				effects = { Health = 5, Happiness = 3 },
				setFlags = { plays_soccer = true },
				hintCareer = "sports",
				feedText = "You made the soccer team! Go team!",
			},
			{
				text = "Basketball",
				effects = { Health = 5, Happiness = 3 },
				setFlags = { plays_basketball = true },
				hintCareer = "sports",
				feedText = "You're on the basketball team now!",
			},
			{
				text = "Swimming",
				effects = { Health = 7 },
				setFlags = { swimmer = true },
				hintCareer = "sports",
				feedText = "You joined the swim team. Great for your health!",
			},
			{
				text = "Martial arts",
				effects = { Health = 5, Smarts = 2 },
				setFlags = { martial_artist = true },
				feedText = "You started learning martial arts. Discipline and strength!",
			},
			{
				text = "I'm not sporty",
				effects = { },
				feedText = "Sports aren't really your thing, and that's okay.",
			},
		},
	},

	{
		id = "music_lessons",
		title = "Music Lessons",
		emoji = "🎹",
		category = "hobby",
		text = "Your parents are offering to pay for music lessons.",
		question = "What instrument interests you?",
		minAge = 6, maxAge = 10,
		baseChance = 0.6,
		cooldown = 4,
		choices = {
			{
				text = "Piano",
				effects = { Smarts = 3, Happiness = 3 },
				setFlags = { plays_piano = true },
				hintCareer = "creative",
				feedText = "You started piano lessons. Classical training!",
			},
			{
				text = "Guitar",
				effects = { Happiness = 5, Looks = 2 },
				setFlags = { plays_guitar = true },
				hintCareer = "entertainment",
				feedText = "You're learning guitar. So cool!",
			},
			{
				text = "Drums",
				effects = { Happiness = 5, Health = 2 },
				setFlags = { plays_drums = true },
				hintCareer = "entertainment",
				feedText = "You took up drums. Your neighbors might not be thrilled.",
			},
			{
				text = "Violin",
				effects = { Smarts = 5 },
				setFlags = { plays_violin = true },
				hintCareer = "creative",
				feedText = "You started violin. A refined choice!",
			},
			{
				text = "No thanks",
				effects = { },
				feedText = "You passed on music lessons for now.",
			},
		},
	},

	-- ══════════════════════════════════════════════════════════════════════
	-- LATE CHILDHOOD (Ages 9-12) - Identity formation, pre-teen drama
	-- ══════════════════════════════════════════════════════════════════════

	{
		id = "first_crush",
		title = "Butterfly Feelings",
		emoji = "💕",
		category = "social",
		text = "You've noticed someone in class makes you feel... different. Your face gets warm when they're around.",
		question = "What do you do about these feelings?",
		minAge = 9, maxAge = 12,
		oneTime = true,
		baseChance = 0.7,
		choices = {
			{
				text = "Write them a secret note",
				effects = { Happiness = {-5, 10} },
				setFlags = { romantic_soul = true },
				feedText = "You slipped a note to your crush. Heart pounding!",
			},
			{
				text = "Tell your best friend",
				effects = { Happiness = 3 },
				setFlags = { shares_feelings = true },
				feedText = "You confided in your best friend about your crush.",
			},
			{
				text = "Keep it to yourself",
				effects = { },
				setFlags = { private_person = true },
				feedText = "You kept your feelings secret. Some things are just for you.",
			},
			{
				text = "Ew, no thanks",
				effects = { Happiness = 2 },
				feedText = "Romance? You've got better things to think about.",
			},
		},
	},

	{
		id = "video_games_discovery",
		title = "Gaming Discovery",
		emoji = "🎮",
		category = "hobby",
		text = "You've discovered video games and they're amazing!",
		question = "What kind of games captivate you?",
		minAge = 7, maxAge = 11,
		baseChance = 0.8,
		cooldown = 5,
		choices = {
			{
				text = "Building/creative games",
				effects = { Smarts = 3, Happiness = 5 },
				setFlags = { creative_gamer = true },
				hintCareer = "tech",
				feedText = "You love building things in games. Future game designer?",
			},
			{
				text = "Adventure/story games",
				effects = { Smarts = 2, Happiness = 5 },
				setFlags = { story_lover = true },
				hintCareer = "creative",
				feedText = "You get lost in epic game stories.",
			},
			{
				text = "Competitive multiplayer",
				effects = { Happiness = 5 },
				setFlags = { competitive_gamer = true },
				feedText = "You love the thrill of competition!",
			},
			{
				text = "Puzzle games",
				effects = { Smarts = 5 },
				setFlags = { puzzle_lover = true },
				hintCareer = "tech",
				feedText = "Puzzle games make your brain happy.",
			},
			{
				text = "Games aren't my thing",
				effects = { },
				feedText = "You prefer other hobbies over gaming.",
			},
		},
	},

	{
		id = "summer_camp",
		title = "Summer Camp",
		emoji = "🏕️",
		category = "experience",
		text = "Your parents are sending you to summer camp!",
		question = "What kind of camp appeals to you?",
		minAge = 8, maxAge = 12,
		baseChance = 0.5,
		cooldown = 2,
		choices = {
			{
				text = "Outdoor adventure camp",
				effects = { Health = 5, Happiness = 5 },
				setFlags = { nature_lover = true },
				feedText = "You learned to hike, camp, and survive in nature!",
			},
			{
				text = "Science camp",
				effects = { Smarts = 7 },
				setFlags = { science_enthusiast = true },
				hintCareer = "science",
				feedText = "You spent the summer doing cool experiments!",
			},
			{
				text = "Arts camp",
				effects = { Happiness = 5, Looks = 3 },
				setFlags = { artistic = true },
				hintCareer = "creative",
				feedText = "You explored painting, sculpture, and more!",
			},
			{
				text = "Sports camp",
				effects = { Health = 7, Happiness = 3 },
				setFlags = { athlete = true },
				hintCareer = "sports",
				feedText = "You trained hard and improved your athletic skills!",
			},
			{
				text = "Computer/coding camp",
				effects = { Smarts = 7 },
				setFlags = { coder = true },
				hintCareer = "tech",
				feedText = "You learned to code! The digital world opens up.",
			},
		},
	},

	{
		id = "pet_responsibility",
		title = "A Pet of Your Own",
		emoji = "🐕",
		category = "responsibility",
		text = "Your parents agree to let you have a pet - but you must take care of it yourself.",
		question = "What pet do you choose?",
		minAge = 8, maxAge = 12,
		oneTime = true,
		baseChance = 0.5,
		requiresFlags = { animal_lover = true }, -- MUST be an animal lover
		choices = {
			{
				text = "A dog",
				effects = { Happiness = 10, Health = 3 },
				setFlags = { has_dog = true },
				hintCareer = "veterinary",
				feedText = "You got a dog! A loyal companion for years to come.",
			},
			{
				text = "A cat",
				effects = { Happiness = 8 },
				setFlags = { has_cat = true },
				feedText = "You got a cat! Independent, but loving.",
			},
			{
				text = "A fish tank",
				effects = { Happiness = 3, Smarts = 2 },
				setFlags = { has_fish = true },
				feedText = "You set up a beautiful fish tank!",
			},
			{
				text = "A hamster or guinea pig",
				effects = { Happiness = 5 },
				setFlags = { has_small_pet = true },
				feedText = "Your little furry friend is adorable!",
			},
		},
	},

	{
		id = "reading_habit",
		title = "Lost in Books",
		emoji = "📚",
		category = "hobby",
		text = "You've discovered the joy of reading! What books capture your imagination?",
		question = "What do you love to read?",
		minAge = 7, maxAge = 12,
		baseChance = 0.6,
		cooldown = 4,
		choices = {
			{
				text = "Fantasy adventures",
				effects = { Smarts = 5, Happiness = 3 },
				setFlags = { fantasy_reader = true },
				hintCareer = "creative",
				feedText = "You devour fantasy books. Magical worlds await!",
			},
			{
				text = "Science and nature",
				effects = { Smarts = 7 },
				setFlags = { nonfiction_reader = true },
				hintCareer = "science",
				feedText = "You love learning facts about the world!",
			},
			{
				text = "Mystery stories",
				effects = { Smarts = 5 },
				setFlags = { mystery_lover = true },
				hintCareer = "law",
				feedText = "You love solving mysteries along with the detective!",
			},
			{
				text = "Comics and graphic novels",
				effects = { Happiness = 5, Smarts = 2 },
				setFlags = { visual_reader = true },
				hintCareer = "creative",
				feedText = "Comics spark your visual imagination!",
			},
			{
				text = "I don't really like reading",
				effects = { },
				feedText = "Books aren't really your thing right now.",
			},
		},
	},

	{
		id = "school_award",
		title = "Recognition",
		emoji = "🏆",
		category = "achievement",
		text = "You've been nominated for a school award!",
		question = "What category?",
		minAge = 7, maxAge = 12,
		baseChance = 0.4,
		cooldown = 3,
		requiresStats = { Smarts = { min = 60 } }, -- MUST be smart enough
		choices = {
			{
				text = "Academic Excellence",
				effects = { Smarts = 3, Happiness = 5 },
				setFlags = { academic_achiever = true },
				feedText = "You won an academic award! Your hard work paid off.",
			},
			{
				text = "Good Citizenship",
				effects = { Happiness = 5 },
				setFlags = { good_citizen = true },
				feedText = "You were recognized for being a great person!",
			},
			{
				text = "Most Improved",
				effects = { Smarts = 2, Happiness = 5 },
				feedText = "You've grown so much this year!",
			},
			{
				text = "Creativity Award",
				effects = { Happiness = 5, Looks = 2 },
				setFlags = { creative_achiever = true },
				hintCareer = "creative",
				feedText = "Your creativity was recognized and celebrated!",
			},
		},
	},

	{
		id = "allowance_decision",
		title = "First Allowance",
		emoji = "💰",
		category = "money",
		text = "Your parents started giving you a weekly allowance. What do you do with it?",
		question = "How do you handle your money?",
		minAge = 8, maxAge = 11,
		oneTime = true,
		choices = {
			{
				text = "Save it all",
				effects = { Smarts = 3, Money = 50 },
				setFlags = { saver = true },
				hintCareer = "finance",
				feedText = "You save every penny. Future financial whiz!",
			},
			{
				text = "Spend it on candy and toys",
				effects = { Happiness = 5, Money = -20 },
				setFlags = { spender = true },
				feedText = "You enjoy your money while you have it!",
			},
			{
				text = "Save some, spend some",
				effects = { Smarts = 2, Happiness = 3, Money = 25 },
				setFlags = { balanced_spender = true },
				feedText = "You're learning balance with money.",
			},
			{
				text = "Try to invest it somehow",
				effects = { Smarts = 5, Money = {-10, 30} },
				setFlags = { entrepreneur = true },
				hintCareer = "finance",
				feedText = "You're already thinking about growing your money!",
			},
		},
	},

	{
		id = "neighborhood_adventure",
		title = "Exploring the Neighborhood",
		emoji = "🗺️",
		category = "adventure",
		text = "You and some friends want to explore beyond your usual boundaries.",
		question = "What do you discover?",
		minAge = 8, maxAge = 12,
		baseChance = 0.6,
		cooldown = 2,
		choices = {
			{
				text = "A hidden creek with wildlife",
				effects = { Happiness = 5, Health = 2 },
				setFlags = { explorer = true },
				hintCareer = "science",
				feedText = "You found a secret nature spot! Adventure awaits.",
			},
			{
				text = "An abandoned building (spooky!)",
				effects = { Happiness = 3, Health = {-3, 0} },
				setFlags = { thrill_seeker = true },
				feedText = "You explored somewhere you probably shouldn't have. Exciting!",
			},
			{
				text = "A kind elderly neighbor",
				effects = { Happiness = 5, Smarts = 2 },
				setFlags = { community_minded = true },
				feedText = "You made friends with an interesting neighbor who has great stories.",
			},
			{
				text = "We get lost and scared",
				effects = { Happiness = -3, Smarts = 2 },
				feedText = "You got lost, but learned an important lesson about preparation.",
			},
		},
	},
}

return ChildhoodEvents
